go get -u github.com/gocql/gocql
go get -u github.com/golang/protobuf/{proto,protoc-gen-go}
go get -u github.com/imkira/go-observer
go get -u github.com/twinj/uuid
go get -u github.com/huandu/facebook
go get -u github.com/google/go-gcm
go get -u github.com/disintegration/imaging
go get -u golang.org/x/crypto/ssh
go get -u gopkg.in/yaml.v2