// Code generated by protoc-gen-go.
// source: protocol.proto
// DO NOT EDIT!

/*
Package protocol is a generated protocol buffer package.

It is generated from these files:
	protocol.proto

It has these top-level messages:
	AyiHeaderV2
	CreateEvent
	CancelEvent
	InviteUsers
	CancelUsersInvitation
	ConfirmAttendance
	ModifyEvent
	VoteChange
	UserPosition
	UserPositionRange
	CreateUserAccount
	NewAuthToken
	AccessToken
	InstanceIDToken
	EventCancelled
	EventExpired
	EventModified
	InvitationCancelled
	AttendanceStatus
	EventChangeProposed
	VotingStatus
	ChangeAccepted
	ChangeDiscarded
	Ok
	Error
	TimeInfo
	ReadEvent
	ListCursor
	ListPublicEvents
	EventsList
	FriendsList
	UserAccount
*/
package protocol

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import common "peeple/areyouin/common"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// NEW AUTH TOKEN
type AuthType int32

const (
	AuthType_A_NATIVE   AuthType = 0
	AuthType_A_FACEBOOK AuthType = 1
)

var AuthType_name = map[int32]string{
	0: "A_NATIVE",
	1: "A_FACEBOOK",
}
var AuthType_value = map[string]int32{
	"A_NATIVE":   0,
	"A_FACEBOOK": 1,
}

func (x AuthType) String() string {
	return proto.EnumName(AuthType_name, int32(x))
}
func (AuthType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

// Header
type AyiHeaderV2 struct {
	Version     uint32 `protobuf:"varint,1,opt,name=version" json:"version,omitempty"`
	Token       uint32 `protobuf:"varint,2,opt,name=token" json:"token,omitempty"`
	Type        uint32 `protobuf:"varint,3,opt,name=type" json:"type,omitempty"`
	PayloadSize uint32 `protobuf:"varint,4,opt,name=payloadSize" json:"payloadSize,omitempty"`
}

func (m *AyiHeaderV2) Reset()                    { *m = AyiHeaderV2{} }
func (m *AyiHeaderV2) String() string            { return proto.CompactTextString(m) }
func (*AyiHeaderV2) ProtoMessage()               {}
func (*AyiHeaderV2) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

// CREATE EVENT
type CreateEvent struct {
	Message      string   `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
	CreatedDate  int64    `protobuf:"varint,2,opt,name=created_date" json:"created_date,omitempty"`
	StartDate    int64    `protobuf:"varint,3,opt,name=start_date" json:"start_date,omitempty"`
	EndDate      int64    `protobuf:"varint,4,opt,name=end_date" json:"end_date,omitempty"`
	Participants []uint64 `protobuf:"varint,5,rep,name=participants" json:"participants,omitempty"`
}

func (m *CreateEvent) Reset()                    { *m = CreateEvent{} }
func (m *CreateEvent) String() string            { return proto.CompactTextString(m) }
func (*CreateEvent) ProtoMessage()               {}
func (*CreateEvent) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

// CANCEL EVENT
type CancelEvent struct {
	EventId uint64 `protobuf:"varint,1,opt,name=event_id" json:"event_id,omitempty"`
	Reason  string `protobuf:"bytes,2,opt,name=reason" json:"reason,omitempty"`
}

func (m *CancelEvent) Reset()                    { *m = CancelEvent{} }
func (m *CancelEvent) String() string            { return proto.CompactTextString(m) }
func (*CancelEvent) ProtoMessage()               {}
func (*CancelEvent) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

// INVITE USERS
type InviteUsers struct {
	EventId      uint64   `protobuf:"varint,1,opt,name=event_id" json:"event_id,omitempty"`
	Participants []uint64 `protobuf:"varint,2,rep,name=participants" json:"participants,omitempty"`
}

func (m *InviteUsers) Reset()                    { *m = InviteUsers{} }
func (m *InviteUsers) String() string            { return proto.CompactTextString(m) }
func (*InviteUsers) ProtoMessage()               {}
func (*InviteUsers) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

// CANCEL USERS INVITATION
type CancelUsersInvitation struct {
	EventId      uint64   `protobuf:"varint,1,opt,name=event_id" json:"event_id,omitempty"`
	Participants []uint64 `protobuf:"varint,2,rep,name=participants" json:"participants,omitempty"`
}

func (m *CancelUsersInvitation) Reset()                    { *m = CancelUsersInvitation{} }
func (m *CancelUsersInvitation) String() string            { return proto.CompactTextString(m) }
func (*CancelUsersInvitation) ProtoMessage()               {}
func (*CancelUsersInvitation) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

// CONFIRM ATTENDANCE
type ConfirmAttendance struct {
	EventId    uint64                    `protobuf:"varint,1,opt,name=event_id" json:"event_id,omitempty"`
	ActionCode common.AttendanceResponse `protobuf:"varint,2,opt,name=action_code,enum=common.AttendanceResponse" json:"action_code,omitempty"`
}

func (m *ConfirmAttendance) Reset()                    { *m = ConfirmAttendance{} }
func (m *ConfirmAttendance) String() string            { return proto.CompactTextString(m) }
func (*ConfirmAttendance) ProtoMessage()               {}
func (*ConfirmAttendance) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

// MODIFY EVENT DATE
// MODIFY EVENT MESSAGE
// MODIFY EVENT
type ModifyEvent struct {
	EventId   uint64 `protobuf:"varint,1,opt,name=event_id" json:"event_id,omitempty"`
	Message   string `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
	StartDate int64  `protobuf:"varint,3,opt,name=start_date" json:"start_date,omitempty"`
	EndDate   int64  `protobuf:"varint,4,opt,name=end_date" json:"end_date,omitempty"`
}

func (m *ModifyEvent) Reset()                    { *m = ModifyEvent{} }
func (m *ModifyEvent) String() string            { return proto.CompactTextString(m) }
func (*ModifyEvent) ProtoMessage()               {}
func (*ModifyEvent) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

// VOTE CHANGE
type VoteChange struct {
	EventId      uint64 `protobuf:"varint,1,opt,name=event_id" json:"event_id,omitempty"`
	ChangeId     uint32 `protobuf:"varint,2,opt,name=change_id" json:"change_id,omitempty"`
	AcceptChange bool   `protobuf:"varint,3,opt,name=accept_change" json:"accept_change,omitempty"`
}

func (m *VoteChange) Reset()                    { *m = VoteChange{} }
func (m *VoteChange) String() string            { return proto.CompactTextString(m) }
func (*VoteChange) ProtoMessage()               {}
func (*VoteChange) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

// USER POSITION
type UserPosition struct {
	GlobalCoordinates *common.Location `protobuf:"bytes,1,opt,name=global_coordinates" json:"global_coordinates,omitempty"`
	EstimationError   float32          `protobuf:"fixed32,2,opt,name=estimation_error" json:"estimation_error,omitempty"`
}

func (m *UserPosition) Reset()                    { *m = UserPosition{} }
func (m *UserPosition) String() string            { return proto.CompactTextString(m) }
func (*UserPosition) ProtoMessage()               {}
func (*UserPosition) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *UserPosition) GetGlobalCoordinates() *common.Location {
	if m != nil {
		return m.GlobalCoordinates
	}
	return nil
}

// USER POSITION RANGE
type UserPositionRange struct {
	RangeInMeters float32 `protobuf:"fixed32,1,opt,name=range_in_meters" json:"range_in_meters,omitempty"`
}

func (m *UserPositionRange) Reset()                    { *m = UserPositionRange{} }
func (m *UserPositionRange) String() string            { return proto.CompactTextString(m) }
func (*UserPositionRange) ProtoMessage()               {}
func (*UserPositionRange) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

// CREATE USER ACCOUNT
type CreateUserAccount struct {
	Name     string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Email    string `protobuf:"bytes,2,opt,name=email" json:"email,omitempty"`
	Password string `protobuf:"bytes,3,opt,name=password" json:"password,omitempty"`
	Phone    string `protobuf:"bytes,4,opt,name=phone" json:"phone,omitempty"`
	Fbid     string `protobuf:"bytes,5,opt,name=fbid" json:"fbid,omitempty"`
	Fbtoken  string `protobuf:"bytes,6,opt,name=fbtoken" json:"fbtoken,omitempty"`
}

func (m *CreateUserAccount) Reset()                    { *m = CreateUserAccount{} }
func (m *CreateUserAccount) String() string            { return proto.CompactTextString(m) }
func (*CreateUserAccount) ProtoMessage()               {}
func (*CreateUserAccount) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

type NewAuthToken struct {
	Pass1 string   `protobuf:"bytes,1,opt,name=pass1" json:"pass1,omitempty"`
	Pass2 string   `protobuf:"bytes,2,opt,name=pass2" json:"pass2,omitempty"`
	Type  AuthType `protobuf:"varint,3,opt,name=type,enum=protocol.AuthType" json:"type,omitempty"`
}

func (m *NewAuthToken) Reset()                    { *m = NewAuthToken{} }
func (m *NewAuthToken) String() string            { return proto.CompactTextString(m) }
func (*NewAuthToken) ProtoMessage()               {}
func (*NewAuthToken) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

// ACCESS GRANTED / USER AUTH / GET ACCESS TOKEN
type AccessToken struct {
	UserId    uint64 `protobuf:"varint,1,opt,name=user_id" json:"user_id,omitempty"`
	AuthToken string `protobuf:"bytes,2,opt,name=auth_token" json:"auth_token,omitempty"`
}

func (m *AccessToken) Reset()                    { *m = AccessToken{} }
func (m *AccessToken) String() string            { return proto.CompactTextString(m) }
func (*AccessToken) ProtoMessage()               {}
func (*AccessToken) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

// INSTANCE ID TOKEN
type InstanceIDToken struct {
	Token string `protobuf:"bytes,1,opt,name=token" json:"token,omitempty"`
}

func (m *InstanceIDToken) Reset()                    { *m = InstanceIDToken{} }
func (m *InstanceIDToken) String() string            { return proto.CompactTextString(m) }
func (*InstanceIDToken) ProtoMessage()               {}
func (*InstanceIDToken) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

// EVENT CANCELLED
type EventCancelled struct {
	EventId uint64 `protobuf:"varint,1,opt,name=event_id" json:"event_id,omitempty"`
	Reason  string `protobuf:"bytes,2,opt,name=reason" json:"reason,omitempty"`
}

func (m *EventCancelled) Reset()                    { *m = EventCancelled{} }
func (m *EventCancelled) String() string            { return proto.CompactTextString(m) }
func (*EventCancelled) ProtoMessage()               {}
func (*EventCancelled) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

// EVENT EXPIRED
type EventExpired struct {
	EventId uint64 `protobuf:"varint,1,opt,name=event_id" json:"event_id,omitempty"`
}

func (m *EventExpired) Reset()                    { *m = EventExpired{} }
func (m *EventExpired) String() string            { return proto.CompactTextString(m) }
func (*EventExpired) ProtoMessage()               {}
func (*EventExpired) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

// EVENT DATE MODIFIED
// EVENT MESSAGE MODIFIED
// EVENT MODIFIED
type EventModified struct {
	EventId   uint64 `protobuf:"varint,1,opt,name=event_id" json:"event_id,omitempty"`
	StartDate int64  `protobuf:"varint,2,opt,name=start_date" json:"start_date,omitempty"`
	EndDate   int64  `protobuf:"varint,3,opt,name=end_date" json:"end_date,omitempty"`
	Message   string `protobuf:"bytes,4,opt,name=message" json:"message,omitempty"`
}

func (m *EventModified) Reset()                    { *m = EventModified{} }
func (m *EventModified) String() string            { return proto.CompactTextString(m) }
func (*EventModified) ProtoMessage()               {}
func (*EventModified) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

// INVITATION CANCELLED
type InvitationCancelled struct {
	EventId uint64 `protobuf:"varint,1,opt,name=event_id" json:"event_id,omitempty"`
}

func (m *InvitationCancelled) Reset()                    { *m = InvitationCancelled{} }
func (m *InvitationCancelled) String() string            { return proto.CompactTextString(m) }
func (*InvitationCancelled) ProtoMessage()               {}
func (*InvitationCancelled) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{17} }

// ATTENDANCE STATUS
type AttendanceStatus struct {
	EventId          uint64                     `protobuf:"varint,1,opt,name=event_id" json:"event_id,omitempty"`
	AttendanceStatus []*common.EventParticipant `protobuf:"bytes,2,rep,name=attendance_status" json:"attendance_status,omitempty"`
}

func (m *AttendanceStatus) Reset()                    { *m = AttendanceStatus{} }
func (m *AttendanceStatus) String() string            { return proto.CompactTextString(m) }
func (*AttendanceStatus) ProtoMessage()               {}
func (*AttendanceStatus) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{18} }

func (m *AttendanceStatus) GetAttendanceStatus() []*common.EventParticipant {
	if m != nil {
		return m.AttendanceStatus
	}
	return nil
}

// EVENT CHANGE DATE PROPOSED
// EVENT CHANGE MESSAGE PROPOSED
// EVENT CHANGE PROPOSED
type EventChangeProposed struct {
	EventId   uint64 `protobuf:"varint,1,opt,name=event_id" json:"event_id,omitempty"`
	ChangeId  uint32 `protobuf:"varint,2,opt,name=change_id" json:"change_id,omitempty"`
	StartDate int64  `protobuf:"varint,3,opt,name=start_date" json:"start_date,omitempty"`
	EndDate   int64  `protobuf:"varint,4,opt,name=end_date" json:"end_date,omitempty"`
	Message   string `protobuf:"bytes,5,opt,name=message" json:"message,omitempty"`
}

func (m *EventChangeProposed) Reset()                    { *m = EventChangeProposed{} }
func (m *EventChangeProposed) String() string            { return proto.CompactTextString(m) }
func (*EventChangeProposed) ProtoMessage()               {}
func (*EventChangeProposed) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{19} }

// VOTING STATUS
// VOTING FINISHED
type VotingStatus struct {
	EventId       uint64 `protobuf:"varint,1,opt,name=event_id" json:"event_id,omitempty"`
	ChangeId      uint32 `protobuf:"varint,2,opt,name=change_id" json:"change_id,omitempty"`
	StartDate     int64  `protobuf:"varint,3,opt,name=start_date" json:"start_date,omitempty"`
	EndDate       int64  `protobuf:"varint,4,opt,name=end_date" json:"end_date,omitempty"`
	ElapsedTime   int64  `protobuf:"varint,5,opt,name=elapsed_time" json:"elapsed_time,omitempty"`
	VotesReceived uint32 `protobuf:"varint,6,opt,name=votes_received" json:"votes_received,omitempty"`
	VotesTotal    uint32 `protobuf:"varint,7,opt,name=votes_total" json:"votes_total,omitempty"`
	Finished      bool   `protobuf:"varint,8,opt,name=finished" json:"finished,omitempty"`
}

func (m *VotingStatus) Reset()                    { *m = VotingStatus{} }
func (m *VotingStatus) String() string            { return proto.CompactTextString(m) }
func (*VotingStatus) ProtoMessage()               {}
func (*VotingStatus) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{20} }

// CHANGE ACCEPTED
type ChangeAccepted struct {
	EventId  uint64 `protobuf:"varint,1,opt,name=event_id" json:"event_id,omitempty"`
	ChangeId uint32 `protobuf:"varint,2,opt,name=change_id" json:"change_id,omitempty"`
}

func (m *ChangeAccepted) Reset()                    { *m = ChangeAccepted{} }
func (m *ChangeAccepted) String() string            { return proto.CompactTextString(m) }
func (*ChangeAccepted) ProtoMessage()               {}
func (*ChangeAccepted) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{21} }

// CHANGE DISCARDED
type ChangeDiscarded struct {
	EventId  uint64 `protobuf:"varint,1,opt,name=event_id" json:"event_id,omitempty"`
	ChangeId uint32 `protobuf:"varint,2,opt,name=change_id" json:"change_id,omitempty"`
}

func (m *ChangeDiscarded) Reset()                    { *m = ChangeDiscarded{} }
func (m *ChangeDiscarded) String() string            { return proto.CompactTextString(m) }
func (*ChangeDiscarded) ProtoMessage()               {}
func (*ChangeDiscarded) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{22} }

// OK
type Ok struct {
	Type    int32  `protobuf:"varint,1,opt,name=type" json:"type,omitempty"`
	Payload []byte `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (m *Ok) Reset()                    { *m = Ok{} }
func (m *Ok) String() string            { return proto.CompactTextString(m) }
func (*Ok) ProtoMessage()               {}
func (*Ok) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{23} }

// ERROR
type Error struct {
	Type  int32 `protobuf:"varint,1,opt,name=type" json:"type,omitempty"`
	Error int32 `protobuf:"varint,2,opt,name=error" json:"error,omitempty"`
}

func (m *Error) Reset()                    { *m = Error{} }
func (m *Error) String() string            { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()               {}
func (*Error) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{24} }

// PING/PONG/CLOCK_RESPONSE
type TimeInfo struct {
	CurrentTime int64 `protobuf:"varint,1,opt,name=current_time" json:"current_time,omitempty"`
}

func (m *TimeInfo) Reset()                    { *m = TimeInfo{} }
func (m *TimeInfo) String() string            { return proto.CompactTextString(m) }
func (*TimeInfo) ProtoMessage()               {}
func (*TimeInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{25} }

// READ EVENT
type ReadEvent struct {
	EventId uint64 `protobuf:"varint,1,opt,name=event_id" json:"event_id,omitempty"`
}

func (m *ReadEvent) Reset()                    { *m = ReadEvent{} }
func (m *ReadEvent) String() string            { return proto.CompactTextString(m) }
func (*ReadEvent) ProtoMessage()               {}
func (*ReadEvent) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{26} }

// LIST AUTHORED EVENTS
// LIST PRIVATE EVENTS
// LIST PUBLIC EVENTS
// HISTORY AUTHORED EVENTS
// HISTORY PRIVATE EVENTS
// HISTORY PUBLIC EVENTS
type ListCursor struct {
	Cursor uint32 `protobuf:"varint,1,opt,name=cursor" json:"cursor,omitempty"`
}

func (m *ListCursor) Reset()                    { *m = ListCursor{} }
func (m *ListCursor) String() string            { return proto.CompactTextString(m) }
func (*ListCursor) ProtoMessage()               {}
func (*ListCursor) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{27} }

type ListPublicEvents struct {
	UserCoordinates *common.Location `protobuf:"bytes,1,opt,name=user_coordinates" json:"user_coordinates,omitempty"`
	RangeInMeters   uint32           `protobuf:"varint,2,opt,name=range_in_meters" json:"range_in_meters,omitempty"`
	Cursor          *ListCursor      `protobuf:"bytes,3,opt,name=cursor" json:"cursor,omitempty"`
}

func (m *ListPublicEvents) Reset()                    { *m = ListPublicEvents{} }
func (m *ListPublicEvents) String() string            { return proto.CompactTextString(m) }
func (*ListPublicEvents) ProtoMessage()               {}
func (*ListPublicEvents) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{28} }

func (m *ListPublicEvents) GetUserCoordinates() *common.Location {
	if m != nil {
		return m.UserCoordinates
	}
	return nil
}

func (m *ListPublicEvents) GetCursor() *ListCursor {
	if m != nil {
		return m.Cursor
	}
	return nil
}

// EVENTS LIST
type EventsList struct {
	Event []*common.Event `protobuf:"bytes,1,rep,name=event" json:"event,omitempty"`
}

func (m *EventsList) Reset()                    { *m = EventsList{} }
func (m *EventsList) String() string            { return proto.CompactTextString(m) }
func (*EventsList) ProtoMessage()               {}
func (*EventsList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{29} }

func (m *EventsList) GetEvent() []*common.Event {
	if m != nil {
		return m.Event
	}
	return nil
}

// FRIENDS LIST
type FriendsList struct {
	Friends []*common.Friend `protobuf:"bytes,1,rep,name=friends" json:"friends,omitempty"`
}

func (m *FriendsList) Reset()                    { *m = FriendsList{} }
func (m *FriendsList) String() string            { return proto.CompactTextString(m) }
func (*FriendsList) ProtoMessage()               {}
func (*FriendsList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{30} }

func (m *FriendsList) GetFriends() []*common.Friend {
	if m != nil {
		return m.Friends
	}
	return nil
}

// USER ACCOUNT
type UserAccount struct {
	Name          string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Email         string `protobuf:"bytes,2,opt,name=email" json:"email,omitempty"`
	Picture       []byte `protobuf:"bytes,3,opt,name=picture,proto3" json:"picture,omitempty"`
	PictureDigest []byte `protobuf:"bytes,4,opt,name=picture_digest,proto3" json:"picture_digest,omitempty"`
}

func (m *UserAccount) Reset()                    { *m = UserAccount{} }
func (m *UserAccount) String() string            { return proto.CompactTextString(m) }
func (*UserAccount) ProtoMessage()               {}
func (*UserAccount) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{31} }

func init() {
	proto.RegisterType((*AyiHeaderV2)(nil), "protocol.AyiHeaderV2")
	proto.RegisterType((*CreateEvent)(nil), "protocol.CreateEvent")
	proto.RegisterType((*CancelEvent)(nil), "protocol.CancelEvent")
	proto.RegisterType((*InviteUsers)(nil), "protocol.InviteUsers")
	proto.RegisterType((*CancelUsersInvitation)(nil), "protocol.CancelUsersInvitation")
	proto.RegisterType((*ConfirmAttendance)(nil), "protocol.ConfirmAttendance")
	proto.RegisterType((*ModifyEvent)(nil), "protocol.ModifyEvent")
	proto.RegisterType((*VoteChange)(nil), "protocol.VoteChange")
	proto.RegisterType((*UserPosition)(nil), "protocol.UserPosition")
	proto.RegisterType((*UserPositionRange)(nil), "protocol.UserPositionRange")
	proto.RegisterType((*CreateUserAccount)(nil), "protocol.CreateUserAccount")
	proto.RegisterType((*NewAuthToken)(nil), "protocol.NewAuthToken")
	proto.RegisterType((*AccessToken)(nil), "protocol.AccessToken")
	proto.RegisterType((*InstanceIDToken)(nil), "protocol.InstanceIDToken")
	proto.RegisterType((*EventCancelled)(nil), "protocol.EventCancelled")
	proto.RegisterType((*EventExpired)(nil), "protocol.EventExpired")
	proto.RegisterType((*EventModified)(nil), "protocol.EventModified")
	proto.RegisterType((*InvitationCancelled)(nil), "protocol.InvitationCancelled")
	proto.RegisterType((*AttendanceStatus)(nil), "protocol.AttendanceStatus")
	proto.RegisterType((*EventChangeProposed)(nil), "protocol.EventChangeProposed")
	proto.RegisterType((*VotingStatus)(nil), "protocol.VotingStatus")
	proto.RegisterType((*ChangeAccepted)(nil), "protocol.ChangeAccepted")
	proto.RegisterType((*ChangeDiscarded)(nil), "protocol.ChangeDiscarded")
	proto.RegisterType((*Ok)(nil), "protocol.Ok")
	proto.RegisterType((*Error)(nil), "protocol.Error")
	proto.RegisterType((*TimeInfo)(nil), "protocol.TimeInfo")
	proto.RegisterType((*ReadEvent)(nil), "protocol.ReadEvent")
	proto.RegisterType((*ListCursor)(nil), "protocol.ListCursor")
	proto.RegisterType((*ListPublicEvents)(nil), "protocol.ListPublicEvents")
	proto.RegisterType((*EventsList)(nil), "protocol.EventsList")
	proto.RegisterType((*FriendsList)(nil), "protocol.FriendsList")
	proto.RegisterType((*UserAccount)(nil), "protocol.UserAccount")
	proto.RegisterEnum("protocol.AuthType", AuthType_name, AuthType_value)
}

var fileDescriptor0 = []byte{
	// 1001 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x9c, 0x55, 0xdf, 0x6f, 0x1a, 0x47,
	0x10, 0xae, 0xc1, 0x38, 0x30, 0x60, 0x8c, 0xcf, 0x49, 0x8b, 0xd2, 0x44, 0xb5, 0xb6, 0x91, 0x6a,
	0x59, 0x11, 0x55, 0x89, 0xd2, 0xd7, 0x8a, 0x10, 0xa2, 0xa0, 0xa6, 0x36, 0xb2, 0x5d, 0xab, 0x7d,
	0x3a, 0x2d, 0x77, 0x0b, 0x5e, 0xe5, 0xd8, 0xbd, 0xee, 0x2e, 0xa4, 0x54, 0xea, 0xbf, 0xd4, 0xbf,
	0xb1, 0xb3, 0xb3, 0xfc, 0x4a, 0x8a, 0x2b, 0x94, 0x97, 0xd3, 0xed, 0xec, 0xcc, 0x37, 0x3b, 0xdf,
	0x7e, 0x33, 0x0b, 0xf5, 0xdc, 0x68, 0xa7, 0x13, 0x9d, 0xb5, 0xe8, 0x27, 0x2a, 0x2f, 0xd7, 0x8f,
	0x21, 0xd1, 0x46, 0x04, 0x2b, 0x1b, 0x40, 0xb5, 0x33, 0x97, 0x6f, 0x05, 0x4f, 0x85, 0xb9, 0x6d,
	0x47, 0x47, 0xf0, 0x60, 0x26, 0x8c, 0x95, 0x5a, 0x35, 0xf7, 0x4e, 0xf7, 0xce, 0x0e, 0xa3, 0x43,
	0x28, 0x39, 0xfd, 0x5e, 0xa8, 0x66, 0x81, 0x96, 0x35, 0xd8, 0x77, 0xf3, 0x5c, 0x34, 0x8b, 0xb4,
	0x3a, 0x81, 0x6a, 0xce, 0xe7, 0x99, 0xe6, 0xe9, 0xb5, 0xfc, 0x4b, 0x34, 0xf7, 0xbd, 0x91, 0xe5,
	0x50, 0xed, 0x1a, 0xc1, 0x9d, 0xe8, 0xcd, 0x84, 0x72, 0x1e, 0x71, 0x22, 0xac, 0xe5, 0x63, 0x41,
	0x88, 0x95, 0xe8, 0x21, 0xd4, 0x12, 0xda, 0x4f, 0xe3, 0x14, 0xbf, 0x04, 0x5c, 0x8c, 0x22, 0x00,
	0xeb, 0xb8, 0x71, 0xc1, 0x56, 0x24, 0x5b, 0x03, 0xca, 0x42, 0x2d, 0xbc, 0xf6, 0xc9, 0x82, 0xb1,
	0x39, 0x3a, 0xc9, 0x44, 0xe6, 0x5c, 0x39, 0xdb, 0x2c, 0x9d, 0x16, 0xcf, 0xf6, 0xd9, 0xf7, 0x98,
	0x91, 0xab, 0x44, 0x64, 0x21, 0xa3, 0x0f, 0xf3, 0x3f, 0xb1, 0x4c, 0x29, 0xe5, 0x7e, 0x54, 0x87,
	0x03, 0xcc, 0x68, 0x75, 0xa8, 0xa2, 0xc2, 0x5e, 0x42, 0xb5, 0xaf, 0x66, 0xd2, 0x89, 0x5f, 0x2d,
	0x16, 0xbb, 0x25, 0xe0, 0xd3, 0x3c, 0x05, 0xca, 0xf3, 0x13, 0x3c, 0x0a, 0x79, 0x28, 0x8c, 0x10,
	0xb8, 0x43, 0xaa, 0x76, 0x06, 0xb8, 0x85, 0xe3, 0xae, 0x56, 0x23, 0x69, 0x26, 0x1d, 0xe7, 0xb0,
	0x34, 0x0f, 0xb6, 0x25, 0x18, 0xeb, 0xe1, 0x89, 0x07, 0x8e, 0x13, 0x9d, 0x06, 0x82, 0xea, 0xed,
	0xc7, 0xad, 0x44, 0x4f, 0x26, 0x5a, 0xb5, 0xd6, 0xa1, 0x57, 0xc2, 0xe6, 0x5a, 0x59, 0x81, 0xb8,
	0xd5, 0x5f, 0x74, 0x2a, 0x47, 0xf3, 0xfb, 0x08, 0xd8, 0xb8, 0x04, 0x62, 0x60, 0x37, 0xba, 0xd9,
	0x5b, 0x80, 0x5b, 0xed, 0x44, 0xf7, 0x8e, 0xab, 0xf1, 0xb6, 0x83, 0x1e, 0x43, 0x25, 0xa1, 0x3d,
	0x6f, 0x0a, 0x02, 0x79, 0x04, 0x87, 0x3c, 0x49, 0x44, 0xee, 0xe2, 0xb0, 0x43, 0xd8, 0x65, 0x3c,
	0x61, 0xcd, 0x93, 0x36, 0xd0, 0x56, 0x12, 0x63, 0xcf, 0x21, 0x1a, 0x67, 0x7a, 0xc8, 0x33, 0x2c,
	0x51, 0x9b, 0x54, 0x2a, 0x4c, 0x6a, 0x09, 0xb5, 0xda, 0x6e, 0x2c, 0x2b, 0x7d, 0xa7, 0x93, 0xc0,
	0x6f, 0x13, 0x1a, 0xc2, 0x3a, 0x39, 0xa1, 0x55, 0x2c, 0x8c, 0xd1, 0x86, 0xd2, 0x15, 0xd8, 0x73,
	0x38, 0xde, 0xc4, 0xbd, 0xa2, 0x83, 0x7e, 0x05, 0x47, 0x26, 0x9c, 0x4a, 0xc5, 0x13, 0xe1, 0xf0,
	0xae, 0x08, 0xb9, 0x80, 0xd2, 0x3c, 0x0e, 0xd2, 0xf4, 0x31, 0x9d, 0x24, 0xd1, 0x53, 0x64, 0x0b,
	0x25, 0xad, 0xf8, 0x64, 0xa9, 0x4e, 0xd4, 0xbb, 0x98, 0x70, 0x99, 0x2d, 0x78, 0xc2, 0x9a, 0x73,
	0x6e, 0xed, 0x07, 0x3c, 0x23, 0x55, 0x42, 0x0e, 0xf9, 0x9d, 0x56, 0x81, 0xa2, 0x8a, 0x8f, 0x1e,
	0x0d, 0xb1, 0xfa, 0x12, 0xad, 0x90, 0xe7, 0xd1, 0x30, 0xf4, 0xcb, 0x01, 0x29, 0xed, 0x02, 0x6a,
	0x17, 0xe2, 0x43, 0x67, 0xea, 0xee, 0x6e, 0xbc, 0x95, 0xa2, 0x11, 0xef, 0x87, 0x75, 0x36, 0xbf,
	0x6c, 0x2f, 0xb2, 0x9d, 0x6e, 0x74, 0x57, 0xbd, 0x1d, 0xb5, 0x56, 0x1d, 0x4c, 0x00, 0xb8, 0xc3,
	0xda, 0xd8, 0xae, 0x48, 0xaf, 0xb5, 0x01, 0x0e, 0xf3, 0x4d, 0xb1, 0x94, 0xf5, 0x8d, 0xe0, 0xbd,
	0x72, 0xf4, 0x8d, 0xd7, 0x3d, 0x5b, 0x61, 0xa7, 0x70, 0xd4, 0x57, 0x78, 0xdb, 0xa8, 0x98, 0xfe,
	0xeb, 0xd5, 0x31, 0x82, 0x07, 0x1d, 0x03, 0x51, 0xeb, 0xa4, 0x9c, 0xa0, 0xee, 0x4c, 0xa4, 0x3b,
	0xf4, 0xd0, 0x29, 0xd4, 0x28, 0xa6, 0xf7, 0x67, 0x2e, 0xcd, 0xb6, 0x08, 0xf6, 0x1b, 0x1c, 0x92,
	0x07, 0x49, 0x53, 0x6e, 0x05, 0xfd, 0x58, 0x86, 0x85, 0xff, 0xc8, 0x30, 0x08, 0x73, 0x43, 0xbd,
	0x44, 0x3a, 0xfb, 0x0e, 0x4e, 0xd6, 0xdd, 0xf7, 0x3f, 0x87, 0x66, 0xbf, 0x43, 0x63, 0xdd, 0x2e,
	0xd7, 0xe8, 0x3f, 0xdd, 0xd6, 0xed, 0x2f, 0xe0, 0x98, 0xaf, 0xbc, 0x62, 0x4b, 0x6e, 0xd4, 0xb1,
	0xd5, 0x76, 0x73, 0xa9, 0x45, 0xaa, 0x64, 0xb0, 0x6e, 0x69, 0xf6, 0x07, 0x9c, 0x04, 0xce, 0x48,
	0xe6, 0x03, 0xa3, 0x73, 0x6d, 0xb7, 0xd6, 0xb8, 0xa5, 0x49, 0x76, 0x1b, 0x76, 0x1b, 0x65, 0x93,
	0xba, 0xd8, 0x3f, 0x7b, 0x50, 0xc3, 0x7e, 0x94, 0x6a, 0x7c, 0x6f, 0x29, 0x9f, 0x9d, 0x0c, 0x07,
	0x96, 0xc8, 0x78, 0x8e, 0x25, 0xc4, 0xd8, 0x68, 0x21, 0x63, 0x31, 0xfa, 0x12, 0xea, 0x33, 0x1c,
	0x00, 0x36, 0x36, 0x22, 0x11, 0x72, 0x26, 0x52, 0x92, 0x35, 0x0d, 0xfe, 0x60, 0x77, 0xda, 0xf1,
	0xac, 0xf9, 0x80, 0x8c, 0x08, 0x3a, 0x92, 0x4a, 0xda, 0x3b, 0x74, 0x2b, 0x53, 0xd7, 0xbf, 0x84,
	0x7a, 0xa0, 0xa7, 0x43, 0x23, 0x61, 0x47, 0x7a, 0xd8, 0x8f, 0x70, 0x14, 0xc2, 0x5e, 0x4b, 0x9b,
	0x70, 0x93, 0xee, 0x1a, 0xf7, 0x2d, 0x14, 0x2e, 0xdf, 0xaf, 0x9e, 0x28, 0xef, 0x56, 0xf2, 0x24,
	0x2e, 0x9e, 0x28, 0x72, 0xaa, 0xb1, 0x67, 0x50, 0xea, 0xf9, 0x01, 0xf2, 0x89, 0x9f, 0xef, 0xfb,
	0xd5, 0x5c, 0x29, 0xa1, 0xba, 0xcb, 0x37, 0x48, 0x43, 0x5f, 0x8d, 0x34, 0x3d, 0x58, 0x53, 0x63,
	0x7c, 0x76, 0xa2, 0x66, 0x8f, 0x66, 0xe3, 0x53, 0xa8, 0x5c, 0xe1, 0xab, 0x79, 0xcf, 0xc4, 0x65,
	0x4f, 0x00, 0xde, 0x49, 0xeb, 0xba, 0x53, 0x63, 0x31, 0x17, 0x36, 0x4f, 0x42, 0x7f, 0xe1, 0x55,
	0x65, 0x7f, 0x43, 0xc3, 0xef, 0x0e, 0xa6, 0xc3, 0x4c, 0x26, 0x04, 0x61, 0xa3, 0x73, 0x68, 0x50,
	0x2f, 0xef, 0x32, 0x10, 0xb7, 0x4c, 0xb8, 0x70, 0xd9, 0xcf, 0x56, 0x89, 0x8a, 0x14, 0xfa, 0x70,
	0x3d, 0x43, 0xd6, 0xc7, 0x61, 0xe7, 0x00, 0x21, 0xa9, 0xb7, 0x45, 0x4f, 0xb0, 0x74, 0xbf, 0xc2,
	0x6c, 0x5e, 0xf2, 0x87, 0x1f, 0x49, 0x9e, 0xb5, 0xa0, 0xfa, 0xc6, 0x48, 0x54, 0x4b, 0x70, 0xfe,
	0x06, 0x27, 0x5c, 0x58, 0x2e, 0xdc, 0xeb, 0x4b, 0xf7, 0xe0, 0xc5, 0xae, 0xa1, 0xba, 0xf3, 0x74,
	0xf5, 0x97, 0x23, 0x13, 0x37, 0x35, 0x41, 0x97, 0x35, 0xaf, 0xb7, 0x85, 0x21, 0x4e, 0xe5, 0x18,
	0x67, 0x3e, 0xa9, 0xb3, 0x76, 0x7e, 0x06, 0xe5, 0xe5, 0x08, 0x44, 0xc4, 0x72, 0x27, 0xbe, 0xe8,
	0xdc, 0xf4, 0x6f, 0x7b, 0x8d, 0x2f, 0x90, 0x59, 0xe8, 0xc4, 0x6f, 0x3a, 0xdd, 0xde, 0xab, 0xcb,
	0xcb, 0x9f, 0x1b, 0x7b, 0xaf, 0x9e, 0xc2, 0xd7, 0xc2, 0xb6, 0x72, 0x21, 0xf2, 0x4c, 0xb4, 0xb8,
	0x11, 0x73, 0x3d, 0x95, 0x6a, 0x45, 0xc2, 0xf0, 0x80, 0xfe, 0x5e, 0xfc, 0x1b, 0x00, 0x00, 0xff,
	0xff, 0x9a, 0x67, 0x0f, 0xa2, 0x1d, 0x09, 0x00, 0x00,
}
